/*
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package com.sun.xml.bind.util;

import java.text.DateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;

/**
 * Converts Calendar formatter as a string into a Calendar object.
 * 
 * This method is used when xs:date/xs:time/xs:dateTime are used
 * as constant properties.
 * 
 * @since JAXB1.0
 * @author
 * 	Kohsuke Kawaguchi (kohsuke.kawaguchi@sun.com)
 */
public class CalendarConv {
    /**
     * DateFormat used to convert a string into a Calendar object.
     */
    public static final DateFormat formatter =
        DateFormat.getDateTimeInstance( DateFormat.FULL, DateFormat.FULL, Locale.ENGLISH );

    public static Calendar createCalendar( String formattedDate ) {
        try {
            Calendar c = new GregorianCalendar();
            c.setTime(formatter.parse(formattedDate));
            return c;
        } catch( ParseException e ) {
            // since "formattedDate" is generated by the compiler,
            // we don't expect this error to happen
            throw new Error(e.getMessage());
        }
    }
}
