/*
 * @(#)$Id: XalanBugWorkaroundFilter.java,v 1.2 2005-09-10 19:08:32 kohsuke Exp $
 */

/*
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at
 * https://jwsdp.dev.java.net/CDDLv1.0.html
 * See the License for the specific language governing
 * permissions and limitations under the License.
 * 
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://jwsdp.dev.java.net/CDDLv1.0.html  If applicable,
 * add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your
 * own identifying information: Portions Copyright [yyyy]
 * [name of copyright owner]
 */
package com.sun.tools.xmlpp;

import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.XMLFilterImpl;

/**
 * Fixes error in the SAX events generated by Xalan. 
 * 
 * @author
 *     Kohsuke Kawaguchi (kohsuke.kawaguchi@sun.com)
 */
public class XalanBugWorkaroundFilter extends XMLFilterImpl {
    
    public XalanBugWorkaroundFilter( ContentHandler next ) {
        this.setContentHandler(next);
    }
    
    public void startElement(String uri, String local, String qname, Attributes arg3) throws SAXException {
        if(uri==null)   uri="";
        super.startElement(uri, local, qname, arg3);
    }

    public void endElement(String uri, String local, String qname) throws SAXException {
        if(uri==null)   uri="";
        super.endElement(uri, local, qname);
    }
}
